### PR TITLE
upgrade lodash package to fix security

### PR DESCRIPTION
**Pull request by iTechDhaval**
https://www.npmjs.com/advisories/1065

### CODE REVIEW

**Comment by yortus** [comment]
Thanks @iTechDhaval! 

If I understand the fibers readme correctly, I think going from fibers@2 to fibers@4 should require a major version bump since it will break existing users who are on any version of node earlier than v10.

It might be better to split this into two PRs - one for the lodash bump with a minor version bump, and a second PR to update fibers and give this lib a major version bump.

**Comment by iTechDhaval** [comment]
It make sense I will create two separate pr for both of them.

**Comment by iTechDhaval** [comment]
> Thanks @iTechDhaval!
> 
> If I understand the fibers readme correctly, I think going from fibers@2 to fibers@4 should require a major version bump since it will break existing users who are on any version of node earlier than v10.
> 
> It might be better to split this into two PRs - one for the lodash bump with a minor version bump, and a second PR to update fibers and give this lib a major version bump.

Changed pull request to upgrade lodash package only.

**Comment by yortus** [comment]
Thanks @iTechDhaval

**Pull request merged**
